### ISSUE TITLE
Commands For Extracting Brain Properties From the Glasser 2016 Atlas? 

### ISSUE THREAD

**Issue by RobertJirsaraie** [tobias-kaufmann/brainage#1]
I would like to run this model on a dataset but am having trouble recreating the features spreadsheet. This is a little complicated to me since the Glasser 2016 Atlas is not one of FreeSurfers default atlases, so I am wondering if you could share the commands you used to extract these data from those parcels. 

I am trying to make everything as reproducible as possible, so I thought asking the authors directly would be better than to keep trying to figure it out on my own. Thank you for sharing this awesome tool.

**Comment by RobertJirsaraie** [comment]
I think the command I need is mris_anatomical_stats, but it requires that I have an "annotation" or "label" file. Is it possible for someone to share this with me or help me walk through creating them for myself. I already have the Glasser 2016 atlas and my freesurfer files registered to fsaverage in my subjects_dir.

**Comment by tobias-kaufmann** [comment]
Below the procedure in a nutshell. 

For each subject run something like:
`mri_surf2surf --srcsubject fsaverage --trgsubject ${SUBNAME} --hemi lh --sval-annot HCP-MMP1/lh.HCP-MMP1.annot --tval $SUBJECTS_DIR/${SUBNAME}/label/lh.HCP-MMP1.annot`

`mri_surf2surf --srcsubject fsaverage --trgsubject ${SUBNAME} --hemi rh --sval-annot HCP-MMP1/rh.HCP-MMP1.annot --tval $SUBJECTS_DIR/${SUBNAME}/label/rh.HCP-MMP1.annot`

`mris_anatomical_stats -mgz -cortex $SUBJECTS_DIR/${SUBNAME}/label/lh.cortex.label -f $SUBJECTS_DIR/${SUBNAME}/stats/lh.HCP-MMP1.stats -b -a $SUBJECTS_DIR/${SUBNAME}/label/lh.HCP-MMP1.annot ${SUBNAME} lh white` 

`mris_anatomical_stats -mgz -cortex $SUBJECTS_DIR/${SUBNAME}/label/rh.cortex.label -f $SUBJECTS_DIR/${SUBNAME}/stats/rh.HCP-MMP1.stats -b -a $SUBJECTS_DIR/${SUBNAME}/label/rh.HCP-MMP1.annot ${SUBNAME} rh white`

--
After running the above commands for all subjects, you would compile the features into subject x feature tables. You need a list of subject names for that, e.g. "set subs=\`cat yoursubjectList\`"

`aparcstats2table --subjects $subs --hemi lh --parc HCP-MMP1 --meas thickness --tablefile $OUTDIR/HCP/lh.thickness.HCP-MMP1.txt`

`aparcstats2table --subjects $subs --hemi rh --parc HCP-MMP1 --meas thickness --tablefile $OUTDIR/HCP/rh.thickness.HCP-MMP1.txt`

`aparcstats2table --subjects $subs --hemi lh --parc HCP-MMP1 --meas area --tablefile $OUTDIR/HCP/lh.area.HCP-MMP1.txt` 

`aparcstats2table --subjects $subs --hemi rh --parc HCP-MMP1 --meas area --tablefile $OUTDIR/HCP/rh.area.HCP-MMP1.txt`

`aparcstats2table --subjects $subs --hemi lh --parc HCP-MMP1 --meas volume --tablefile $OUTDIR/HCP/lh.volume.HCP-MMP1.txt`

`aparcstats2table --subjects $subs --hemi rh --parc HCP-MMP1 --meas volume --tablefile $OUTDIR/HCP/rh.volume.HCP-MMP1.txt`
